name: neutron
version: ocata
summary: OpenStack Network Service (neutron)
description: OpenStack Network Service (neutron)
confinement: strict
grade: devel

apps:
  api:
    command: snap-openstack neutron-server
    daemon: simple
    plugs:
      - network
      - network-bind
  manage:
    command: snap-openstack neutron-db-manage
    plugs:
      - network

parts:
  neutron:
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/neutron/neutron-master.tar.gz
    python-packages:
      - pymysql
      - git+https://github.com/openstack-snaps/snap.openstack#egg=snap.openstack
    constraints: https://raw.githubusercontent.com/openstack/requirements/master/upper-constraints.txt
    build-packages:
      - libffi-dev
      - libssl-dev
      - pkg-config
  templates:
    after:
      - neutron
    plugin: openstack
    source: conf
  # TODO: replace below with scriplets once implemented in snapcraft
  config:
    after:
      - neutron
    plugin: openstack
    source: http://tarballs.openstack.org/neutron/neutron-master.tar.gz
    generate-config:
      - tox -e genconfig
    organize:
      etc/*.conf: etc/neutron/
      etc/*.ini: etc/neutron/
      etc/*.json: etc/neutron/
      etc/*.sample: etc/neutron/
      etc/neutron.conf.sample: etc/neutron/neutron.conf
      etc/neutron/plugins/ml2/ml2_conf.ini.sample: etc/neutron/plugins/ml2/ml2_conf.ini
      etc/rootwrap.d/*.filters: etc/neutron/rootwrap.d/
    filesets:
      etc:
        - etc/neutron/*.conf
        - etc/neutron/*.ini
        - etc/neutron/*.json
        - etc/neutron/*.sample
        - etc/neutron/plugins/ml2/*.ini
        - etc/neutron/plugins/ml2/*.sample
        - etc/neutron/rootwrap.d/*.filters
    stage: [$etc]
    snap: [$etc]
